--
--  trigger: TR_STG_COLUMN_CONFIG_MODIFIED_TS
--  Trigger to update the modified timestamp for STG_COLUMN_CONFIG
--

CREATE TRIGGER META.TR_STG_COLUMN_CONFIG_MODIFIED_TS
ON META.STG_COLUMN_CONFIG
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE t
    SET MODIFIED_TS = SYSDATETIME()
    FROM META.STG_COLUMN_CONFIG t
    INNER JOIN inserted i
        ON i.OBJECT_ID = t.OBJECT_ID
       AND i.COLUMN_NAME = t.COLUMN_NAME
    INNER JOIN deleted d
        ON d.OBJECT_ID = i.OBJECT_ID
       AND d.COLUMN_NAME = i.COLUMN_NAME
    WHERE
           ISNULL(i.INCLUDE_IN_STG, 0) <> ISNULL(d.INCLUDE_IN_STG, 0)
        OR ISNULL(i.TEXT_STANDARDIZATION, '') <> ISNULL(d.TEXT_STANDARDIZATION, '');
END;
