
ALTER TABLE [META].[DQ_PROFILE] DROP CONSTRAINT [CK_DQ_PROFILE_RULE_TYPE]
GO

ALTER TABLE [META].[DQ_PROFILE] DROP CONSTRAINT [CK_DQ_PROFILE_RULE_SCOPE]
GO

ALTER TABLE [META].[DQ_PROFILE] DROP CONSTRAINT [FK_DQ_PROFILE_RUN]
GO

ALTER TABLE [META].[DQ_PROFILE] DROP CONSTRAINT [FK_DQ_PROFILE_RULE]
GO

ALTER TABLE [META].[DQ_PROFILE] DROP CONSTRAINT [FK_DQ_PROFILE_OBJECT]
GO

ALTER TABLE [META].[DQ_PROFILE] DROP CONSTRAINT [DF_DQ_PROFILE_PROFILE_TS]
GO

/****** Object:  Table [META].[DQ_PROFILE]    Script Date: 4. 08. 2026 09:45:13 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[META].[DQ_PROFILE]') AND type in (N'U'))
DROP TABLE [META].[DQ_PROFILE]
GO

/****** Object:  Table [META].[DQ_PROFILE]    Script Date: 4. 08. 2026 09:45:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [META].[DQ_PROFILE](
	[PROFILE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RUN_ID] [bigint] NOT NULL,
	[RULE_ID] [bigint] NOT NULL,
	[OBJECT_ID] [bigint] NOT NULL,
	[OBJECT_NAME] [varchar](255) NOT NULL,
	[COLUMN_NAME] [varchar](255) NULL,
	[RULE_SCOPE] [varchar](20) NOT NULL,
	[RULE_TYPE] [varchar](50) NOT NULL,
	[RULE_NAME] [varchar](255) NOT NULL,
	[RULE_ORDER] [int] NULL,
	[PROFILE_VALUE_NUMERIC] [decimal](38, 10) NULL,
	[PROFILE_VALUE_TEXT] [varchar](4000) NULL,
	[PROFILE_UNIT] [varchar](50) NULL,
	[PROFILE_TS] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_DQ_PROFILE] PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [META].[DQ_PROFILE] ADD  CONSTRAINT [DF_DQ_PROFILE_PROFILE_TS]  DEFAULT (sysdatetime()) FOR [PROFILE_TS]
GO

ALTER TABLE [META].[DQ_PROFILE]  WITH CHECK ADD  CONSTRAINT [FK_DQ_PROFILE_OBJECT] FOREIGN KEY([OBJECT_ID])
REFERENCES [META].[SOURCE_OBJECT] ([OBJECT_ID])
GO

ALTER TABLE [META].[DQ_PROFILE] CHECK CONSTRAINT [FK_DQ_PROFILE_OBJECT]
GO

ALTER TABLE [META].[DQ_PROFILE]  WITH CHECK ADD  CONSTRAINT [FK_DQ_PROFILE_RULE] FOREIGN KEY([RULE_ID])
REFERENCES [META].[SOURCE_PROFILE_RULE] ([RULE_ID])
GO

ALTER TABLE [META].[DQ_PROFILE] CHECK CONSTRAINT [FK_DQ_PROFILE_RULE]
GO

ALTER TABLE [META].[DQ_PROFILE]  WITH CHECK ADD  CONSTRAINT [FK_DQ_PROFILE_RUN] FOREIGN KEY([RUN_ID])
REFERENCES [META].[DWH_RUN] ([RUN_ID])
GO

ALTER TABLE [META].[DQ_PROFILE] CHECK CONSTRAINT [FK_DQ_PROFILE_RUN]
GO

ALTER TABLE [META].[DQ_PROFILE]  WITH CHECK ADD  CONSTRAINT [CK_DQ_PROFILE_RULE_SCOPE] CHECK  (([RULE_SCOPE]='COLUMN' OR [RULE_SCOPE]='OBJECT'))
GO

ALTER TABLE [META].[DQ_PROFILE] CHECK CONSTRAINT [CK_DQ_PROFILE_RULE_SCOPE]
GO

ALTER TABLE [META].[DQ_PROFILE]  WITH CHECK ADD  CONSTRAINT [CK_DQ_PROFILE_RULE_TYPE] CHECK  (([RULE_TYPE]='CUSTOM' OR [RULE_TYPE]='ANOMALY' OR [RULE_TYPE]='REFERENCE' OR [RULE_TYPE]='FRESHNESS' OR [RULE_TYPE]='PATTERN' OR [RULE_TYPE]='DOMAIN' OR [RULE_TYPE]='MIN_MAX' OR [RULE_TYPE]='DISTINCT_PCT' OR [RULE_TYPE]='DISTINCT_COUNT' OR [RULE_TYPE]='NULL_PCT' OR [RULE_TYPE]='NULL_COUNT' OR [RULE_TYPE]='ROW_COUNT'))
GO

ALTER TABLE [META].[DQ_PROFILE] CHECK CONSTRAINT [CK_DQ_PROFILE_RULE_TYPE]
GO


