
ALTER TABLE [META].[DWH_RUN_OBJECT] DROP CONSTRAINT [CK_DWH_RUN_OBJECT_STATUS]
GO

ALTER TABLE [META].[DWH_RUN_OBJECT] DROP CONSTRAINT [CK_DWH_RUN_OBJECT_LAYER]
GO

ALTER TABLE [META].[DWH_RUN_OBJECT] DROP CONSTRAINT [FK_DWH_RUN_OBJECT_RUN]
GO

ALTER TABLE [META].[DWH_RUN_OBJECT] DROP CONSTRAINT [DF_DWH_RUN_OBJECT_STATUS]
GO

ALTER TABLE [META].[DWH_RUN_OBJECT] DROP CONSTRAINT [DF_DWH_RUN_OBJECT_START_TS]
GO

/****** Object:  Table [META].[DWH_RUN_OBJECT]    Script Date: 4. 08. 2026 09:47:35 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[META].[DWH_RUN_OBJECT]') AND type in (N'U'))
DROP TABLE [META].[DWH_RUN_OBJECT]
GO

/****** Object:  Table [META].[DWH_RUN_OBJECT]    Script Date: 4. 08. 2026 09:47:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [META].[DWH_RUN_OBJECT](
	[RUN_OBJECT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RUN_ID] [bigint] NOT NULL,
	[OBJECT_LAYER] [varchar](20) NOT NULL,
	[OBJECT_NAME] [varchar](255) NOT NULL,
	[START_TS] [datetime2](7) NOT NULL,
	[END_TS] [datetime2](7) NULL,
	[DURATION_SEC] [decimal](18, 4) NULL,
	[STATUS] [varchar](20) NOT NULL,
	[ROW_COUNT] [bigint] NULL,
	[ERROR_MESSAGE] [varchar](2000) NULL,
PRIMARY KEY CLUSTERED 
(
	[RUN_OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [META].[DWH_RUN_OBJECT] ADD  CONSTRAINT [DF_DWH_RUN_OBJECT_START_TS]  DEFAULT (sysdatetime()) FOR [START_TS]
GO

ALTER TABLE [META].[DWH_RUN_OBJECT] ADD  CONSTRAINT [DF_DWH_RUN_OBJECT_STATUS]  DEFAULT ('RUNNING') FOR [STATUS]
GO

ALTER TABLE [META].[DWH_RUN_OBJECT]  WITH CHECK ADD  CONSTRAINT [FK_DWH_RUN_OBJECT_RUN] FOREIGN KEY([RUN_ID])
REFERENCES [META].[DWH_RUN] ([RUN_ID])
GO

ALTER TABLE [META].[DWH_RUN_OBJECT] CHECK CONSTRAINT [FK_DWH_RUN_OBJECT_RUN]
GO

ALTER TABLE [META].[DWH_RUN_OBJECT]  WITH CHECK ADD  CONSTRAINT [CK_DWH_RUN_OBJECT_LAYER] CHECK  (([OBJECT_LAYER]='META' OR [OBJECT_LAYER]='MART' OR [OBJECT_LAYER]='DWH' OR [OBJECT_LAYER]='STAG' OR [OBJECT_LAYER]='LAND'))
GO

ALTER TABLE [META].[DWH_RUN_OBJECT] CHECK CONSTRAINT [CK_DWH_RUN_OBJECT_LAYER]
GO

ALTER TABLE [META].[DWH_RUN_OBJECT]  WITH CHECK ADD  CONSTRAINT [CK_DWH_RUN_OBJECT_STATUS] CHECK  (([STATUS]='CANCELLED' OR [STATUS]='SKIPPED' OR [STATUS]='WARNING' OR [STATUS]='FAILED' OR [STATUS]='SUCCESS' OR [STATUS]='RUNNING'))
GO

ALTER TABLE [META].[DWH_RUN_OBJECT] CHECK CONSTRAINT [CK_DWH_RUN_OBJECT_STATUS]
GO


