
ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [CK_SOURCE_PROFILE_RULE_TYPE]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [CK_SOURCE_PROFILE_RULE_SEVERITY]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [CK_SOURCE_PROFILE_RULE_SCOPE]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [FK_SOURCE_PROFILE_RULE_OBJECT]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [DF_SOURCE_PROFILE_RULE_CREATED_TS]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [DF_SOURCE_PROFILE_RULE_ALERT]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [DF_SOURCE_PROFILE_RULE_ENABLED]
GO

/****** Object:  Table [META].[SOURCE_PROFILE_RULE]    Script Date: 4. 08. 2026 09:49:43 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[META].[SOURCE_PROFILE_RULE]') AND type in (N'U'))
DROP TABLE [META].[SOURCE_PROFILE_RULE]
GO

/****** Object:  Table [META].[SOURCE_PROFILE_RULE]    Script Date: 4. 08. 2026 09:49:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [META].[SOURCE_PROFILE_RULE](
	[RULE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[OBJECT_ID] [bigint] NOT NULL,
	[COLUMN_NAME] [varchar](255) NULL,
	[RULE_NAME] [varchar](255) NOT NULL,
	[RULE_TYPE] [varchar](50) NOT NULL,
	[RULE_ENABLED] [bit] NOT NULL,
	[MIN_NUMERIC_VALUE] [decimal](38, 10) NULL,
	[MAX_NUMERIC_VALUE] [decimal](38, 10) NULL,
	[MIN_ROW_COUNT] [bigint] NULL,
	[MAX_ROW_COUNT] [bigint] NULL,
	[MIN_DISTINCT_COUNT] [bigint] NULL,
	[MAX_DISTINCT_COUNT] [bigint] NULL,
	[MAX_NULL_PCT] [decimal](9, 4) NULL,
	[ALLOWED_VALUES] [varchar](4000) NULL,
	[PATTERN] [varchar](1000) NULL,
	[RULE_SCOPE] [varchar](20) NULL,
	[ALERT_ENABLED] [bit] NOT NULL,
	[ALERT_SEVERITY] [varchar](20) NULL,
	[DESCRIPTION] [varchar](2000) NULL,
	[CREATED_TS] [datetime2](0) NOT NULL,
	[MODIFIED_TS] [datetime2](0) NULL,
	[RULE_ORDER] [int] NULL,
 CONSTRAINT [PK_SOURCE_PROFILE_RULE] PRIMARY KEY CLUSTERED 
(
	[RULE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] ADD  CONSTRAINT [DF_SOURCE_PROFILE_RULE_ENABLED]  DEFAULT ((1)) FOR [RULE_ENABLED]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] ADD  CONSTRAINT [DF_SOURCE_PROFILE_RULE_ALERT]  DEFAULT ((0)) FOR [ALERT_ENABLED]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] ADD  CONSTRAINT [DF_SOURCE_PROFILE_RULE_CREATED_TS]  DEFAULT (sysdatetime()) FOR [CREATED_TS]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE]  WITH CHECK ADD  CONSTRAINT [FK_SOURCE_PROFILE_RULE_OBJECT] FOREIGN KEY([OBJECT_ID])
REFERENCES [META].[SOURCE_OBJECT] ([OBJECT_ID])
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] CHECK CONSTRAINT [FK_SOURCE_PROFILE_RULE_OBJECT]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE]  WITH CHECK ADD  CONSTRAINT [CK_SOURCE_PROFILE_RULE_SCOPE] CHECK  (([RULE_SCOPE]='COLUMN' OR [RULE_SCOPE]='OBJECT'))
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] CHECK CONSTRAINT [CK_SOURCE_PROFILE_RULE_SCOPE]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE]  WITH CHECK ADD  CONSTRAINT [CK_SOURCE_PROFILE_RULE_SEVERITY] CHECK  (([ALERT_SEVERITY] IS NULL OR ([ALERT_SEVERITY]='CRITICAL' OR [ALERT_SEVERITY]='ERROR' OR [ALERT_SEVERITY]='WARNING' OR [ALERT_SEVERITY]='INFO')))
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] CHECK CONSTRAINT [CK_SOURCE_PROFILE_RULE_SEVERITY]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE]  WITH CHECK ADD  CONSTRAINT [CK_SOURCE_PROFILE_RULE_TYPE] CHECK  (([RULE_TYPE]='CUSTOM' OR [RULE_TYPE]='ANOMALY' OR [RULE_TYPE]='REFERENCE' OR [RULE_TYPE]='FRESHNESS' OR [RULE_TYPE]='PATTERN' OR [RULE_TYPE]='DOMAIN' OR [RULE_TYPE]='MIN_MAX' OR [RULE_TYPE]='DISTINCT_PCT' OR [RULE_TYPE]='DISTINCT_COUNT' OR [RULE_TYPE]='NULL_PCT' OR [RULE_TYPE]='NULL_COUNT' OR [RULE_TYPE]='ROW_COUNT'))
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] CHECK CONSTRAINT [CK_SOURCE_PROFILE_RULE_TYPE]
GO


