IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[META].[SOURCE_OBJECT]') AND type in (N'U'))
ALTER TABLE [META].[SOURCE_OBJECT] DROP CONSTRAINT IF EXISTS [CK_SOURCE_OBJECT_DWH_LAYER]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[META].[SOURCE_OBJECT]') AND type in (N'U'))
ALTER TABLE [META].[SOURCE_OBJECT] DROP CONSTRAINT IF EXISTS [FK_SOURCE_OBJECT_BUSINESS_DOMAIN]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[META].[SOURCE_OBJECT]') AND type in (N'U'))
ALTER TABLE [META].[SOURCE_OBJECT] DROP CONSTRAINT IF EXISTS [DF_SOURCE_OBJECT_CREATED_TS]
GO

/****** Object:  Index [UX_SOURCE_OBJECT_LAND_OBJECT_NAME]    Script Date: 6. 08. 2026 13:40:49 ******/
DROP INDEX IF EXISTS [UX_SOURCE_OBJECT_LAND_OBJECT_NAME] ON [META].[SOURCE_OBJECT]
GO

/****** Object:  Index [IX_SOURCE_OBJECT_DWH_LAYER]    Script Date: 6. 08. 2026 13:40:49 ******/
DROP INDEX IF EXISTS [IX_SOURCE_OBJECT_DWH_LAYER] ON [META].[SOURCE_OBJECT]
GO

/****** Object:  Index [IX_SOURCE_OBJECT_BUSINESS_DOMAIN]    Script Date: 6. 08. 2026 13:40:49 ******/
DROP INDEX IF EXISTS [IX_SOURCE_OBJECT_BUSINESS_DOMAIN] ON [META].[SOURCE_OBJECT]
GO

/****** Object:  Table [META].[SOURCE_OBJECT]    Script Date: 6. 08. 2026 13:40:49 ******/
DROP TABLE IF EXISTS [META].[SOURCE_OBJECT]
GO

/****** Object:  Table [META].[SOURCE_OBJECT]    Script Date: 6. 08. 2026 13:40:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [META].[SOURCE_OBJECT](
	[OBJECT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SOURCE_SYSTEM] [varchar](100) NOT NULL,
	[SERVER_NAME] [varchar](255) NULL,
	[DATABASE_NAME] [varchar](255) NULL,
	[SCHEMA_NAME] [varchar](255) NULL,
	[OBJECT_NAME] [varchar](255) NOT NULL,
	[LAND_OBJECT_NAME] [varchar](255) NOT NULL,
	[OBJECT_TYPE] [varchar](30) NOT NULL,
	[STATUS] [varchar](20) NOT NULL,
	[LAST_STRUCTURE_HASH] [varbinary](32) NULL,
	[LAST_SEEN_TS] [datetime2](0) NULL,
	[LAST_STRUCTURE_CHANGE_TS] [datetime2](0) NULL,
	[CREATED_TS] [datetime2](0) NOT NULL,
	[BUSINESS_DOMAIN_ID] [bigint] NULL,
	[DWH_LAYER] [varchar](20) NULL,
 CONSTRAINT [PK_SOURCE_OBJECT] PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SOURCE_OBJECT] UNIQUE NONCLUSTERED 
(
	[SOURCE_SYSTEM] ASC,
	[SERVER_NAME] ASC,
	[DATABASE_NAME] ASC,
	[SCHEMA_NAME] ASC,
	[OBJECT_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Index [IX_SOURCE_OBJECT_BUSINESS_DOMAIN]    Script Date: 6. 08. 2026 13:40:50 ******/
CREATE NONCLUSTERED INDEX [IX_SOURCE_OBJECT_BUSINESS_DOMAIN] ON [META].[SOURCE_OBJECT]
(
	[BUSINESS_DOMAIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_SOURCE_OBJECT_DWH_LAYER]    Script Date: 6. 08. 2026 13:40:50 ******/
CREATE NONCLUSTERED INDEX [IX_SOURCE_OBJECT_DWH_LAYER] ON [META].[SOURCE_OBJECT]
(
	[DWH_LAYER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [UX_SOURCE_OBJECT_LAND_OBJECT_NAME]    Script Date: 6. 08. 2026 13:40:50 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_SOURCE_OBJECT_LAND_OBJECT_NAME] ON [META].[SOURCE_OBJECT]
(
	[LAND_OBJECT_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [META].[SOURCE_OBJECT] ADD  CONSTRAINT [DF_SOURCE_OBJECT_CREATED_TS]  DEFAULT (sysdatetime()) FOR [CREATED_TS]
GO

ALTER TABLE [META].[SOURCE_OBJECT]  WITH CHECK ADD  CONSTRAINT [FK_SOURCE_OBJECT_BUSINESS_DOMAIN] FOREIGN KEY([BUSINESS_DOMAIN_ID])
REFERENCES [META].[BUSINESS_DOMAIN] ([BUSINESS_DOMAIN_ID])
GO

ALTER TABLE [META].[SOURCE_OBJECT] CHECK CONSTRAINT [FK_SOURCE_OBJECT_BUSINESS_DOMAIN]
GO

ALTER TABLE [META].[SOURCE_OBJECT]  WITH CHECK ADD  CONSTRAINT [CK_SOURCE_OBJECT_DWH_LAYER] CHECK  (([DWH_LAYER] IS NULL OR ([DWH_LAYER]='META' OR [DWH_LAYER]='MAP' OR [DWH_LAYER]='MART' OR [DWH_LAYER]='FACT' OR [DWH_LAYER]='DIM' OR [DWH_LAYER]='STG' OR [DWH_LAYER]='LAND')))
GO

ALTER TABLE [META].[SOURCE_OBJECT] CHECK CONSTRAINT [CK_SOURCE_OBJECT_DWH_LAYER]
GO


