
/*******************************************************************************
 * Table: META.SOURCE_PROFILE_RULE
 * Description:
 *   Defines profiling rules that drive source data quality checks.
 *   Rules can be scoped to an object or to an individual column and include
 *   thresholds for null counts, distinct counts, row counts, and percent values.
 *
 * Columns include:
 *   OBJECT_ID          reference to META.SOURCE_OBJECT
 *   COLUMN_NAME        optional column name for column-scoped rules
 *   RULE_NAME          human-readable rule identifier
 *   RULE_TYPE          rule kind, such as ROW_COUNT, NULL_COUNT, NULL_PCT,
 *                      DISTINCT_COUNT, DISTINCT_PCT
 *   RULE_ENABLED       flag for rule activation
 *   ALERT_ENABLED      whether rule alerting is enabled
 *   ALERT_SEVERITY     optional severity level for alerts
 *   DESCRIPTION        rule description
 *   CREATED_TS         creation timestamp
 *   MODIFIED_TS        optional last modified timestamp
 *
 * This script drops and recreates the table with constraints and defaults.
 *******************************************************************************/
ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [CK_SOURCE_PROFILE_RULE_TYPE]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [CK_SOURCE_PROFILE_RULE_SEVERITY]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [CK_SOURCE_PROFILE_RULE_SCOPE]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [FK_SOURCE_PROFILE_RULE_OBJECT]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [DF_SOURCE_PROFILE_RULE_CREATED_TS]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [DF_SOURCE_PROFILE_RULE_ALERT]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] DROP CONSTRAINT [DF_SOURCE_PROFILE_RULE_ENABLED]
GO

/****** Object:  Table [META].[SOURCE_PROFILE_RULE]    Script Date: 4. 08. 2026 09:49:43 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[META].[SOURCE_PROFILE_RULE]') AND type in (N'U'))
DROP TABLE [META].[SOURCE_PROFILE_RULE]
GO

/****** Object:  Table [META].[SOURCE_PROFILE_RULE]    Script Date: 4. 08. 2026 09:49:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [META].[SOURCE_PROFILE_RULE]
(
    [RULE_ID] BIGINT IDENTITY(1,1) NOT NULL,
    [OBJECT_ID] BIGINT NOT NULL,
    [COLUMN_NAME] VARCHAR(255) NULL,
    [RULE_NAME] VARCHAR(255) NOT NULL,
    [RULE_TYPE] VARCHAR(50) NOT NULL,
    [RULE_ENABLED] BIT NOT NULL CONSTRAINT [DF_SOURCE_PROFILE_RULE_ENABLED] DEFAULT ((1)),
    [MIN_NUMERIC_VALUE] DECIMAL(38,10) NULL,
    [MAX_NUMERIC_VALUE] DECIMAL(38,10) NULL,
    [MIN_ROW_COUNT] BIGINT NULL,
    [MAX_ROW_COUNT] BIGINT NULL,
    [MIN_DISTINCT_COUNT] BIGINT NULL,
    [MAX_DISTINCT_COUNT] BIGINT NULL,
    [MAX_NULL_PCT] DECIMAL(9,4) NULL,
    [ALLOWED_VALUES] VARCHAR(4000) NULL,
    [PATTERN] VARCHAR(1000) NULL,
    [RULE_SCOPE] VARCHAR(20) NULL CONSTRAINT [CK_SOURCE_PROFILE_RULE_SCOPE] CHECK ([RULE_SCOPE] IN ('COLUMN','OBJECT')),
    [ALERT_ENABLED] BIT NOT NULL CONSTRAINT [DF_SOURCE_PROFILE_RULE_ALERT] DEFAULT ((0)),
    [DESCRIPTION] VARCHAR(2000) NULL,
    [CREATED_TS] DATETIME2(0) NOT NULL CONSTRAINT [DF_SOURCE_PROFILE_RULE_CREATED_TS] DEFAULT (sysdatetime()),
    [MODIFIED_TS] DATETIME2(0) NULL,
    [RULE_ORDER] INT NULL,
    [MIN_VALUE] DECIMAL(38,10) NULL,
    [MAX_VALUE] DECIMAL(38,10) NULL,
    [ALERT_SEVERITY] VARCHAR(20) NULL CONSTRAINT [CK_SOURCE_PROFILE_RULE_SEVERITY] CHECK (
        ALERT_SEVERITY IS NULL OR ALERT_SEVERITY IN ('CRITICAL','ERROR','WARNING','INFO')
    ),
    CONSTRAINT [PK_SOURCE_PROFILE_RULE] PRIMARY KEY CLUSTERED
    (
        [RULE_ID] ASC
    ) WITH (
        PAD_INDEX = OFF,
        STATISTICS_NORECOMPUTE = OFF,
        IGNORE_DUP_KEY = OFF,
        ALLOW_ROW_LOCKS = ON,
        ALLOW_PAGE_LOCKS = ON,
        OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
    )
) ON [PRIMARY]
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] WITH CHECK ADD CONSTRAINT [FK_SOURCE_PROFILE_RULE_OBJECT]
    FOREIGN KEY([OBJECT_ID]) REFERENCES [META].[SOURCE_OBJECT]([OBJECT_ID]);
GO

ALTER TABLE [META].[SOURCE_PROFILE_RULE] WITH CHECK ADD CONSTRAINT [CK_SOURCE_PROFILE_RULE_TYPE]
    CHECK ([RULE_TYPE] IN (
        'CUSTOM', 'ANOMALY', 'REFERENCE', 'FRESHNESS', 'PATTERN', 'DOMAIN',
        'MIN_MAX', 'DISTINCT_PCT', 'DISTINCT_COUNT', 'NULL_PCT', 'NULL_COUNT', 'ROW_COUNT'
    ));
GO


