IF EXISTS (
    SELECT 1
    FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[META].[SOURCE_OBJECT]')
      AND type IN (N'U')
)
BEGIN
    ALTER TABLE [META].[SOURCE_OBJECT] DROP CONSTRAINT IF EXISTS [CK_SOURCE_OBJECT_DWH_LAYER];
    ALTER TABLE [META].[SOURCE_OBJECT] DROP CONSTRAINT IF EXISTS [FK_SOURCE_OBJECT_BUSINESS_DOMAIN];
    ALTER TABLE [META].[SOURCE_OBJECT] DROP CONSTRAINT IF EXISTS [DF_SOURCE_OBJECT_CREATED_TS];
END
GO

DROP INDEX IF EXISTS [UX_SOURCE_OBJECT_LAND_OBJECT_NAME] ON [META].[SOURCE_OBJECT];
DROP INDEX IF EXISTS [IX_SOURCE_OBJECT_DWH_LAYER] ON [META].[SOURCE_OBJECT];
DROP INDEX IF EXISTS [IX_SOURCE_OBJECT_BUSINESS_DOMAIN] ON [META].[SOURCE_OBJECT];
GO

DROP TABLE IF EXISTS [META].[SOURCE_OBJECT];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [META].[SOURCE_OBJECT](
    [OBJECT_ID] [bigint] IDENTITY(1,1) NOT NULL,
    [SOURCE_SYSTEM] [varchar](100) NULL,
    [SERVER_NAME] [varchar](255) NULL,
    [DATABASE_NAME] [varchar](255) NULL,
    [SCHEMA_NAME] [varchar](255) NULL,
    [OBJECT_NAME] [varchar](255) NOT NULL,
    [LAND_OBJECT_NAME] [varchar](255) NULL,
    [OBJECT_TYPE] [varchar](30) NOT NULL,
    [STATUS] [varchar](20) NOT NULL,
    [LAST_STRUCTURE_HASH] [varbinary](32) NULL,
    [LAST_SEEN_TS] [datetime2](0) NULL,
    [LAST_STRUCTURE_CHANGE_TS] [datetime2](0) NULL,
    [CREATED_TS] [datetime2](0) NOT NULL,
    [BUSINESS_DOMAIN_ID] [bigint] NULL,
    [DWH_LAYER] [varchar](20) NULL,
	[OBJECT_ORIGIN] [varchar](20) NULL,
    [INGESTION_METHOD] [varchar](20) NULL,
    [LOAD_TYPE] [varchar](20) NULL,
    [WATERMARK_COLUMN] [varchar](255) NULL,
    [WATERMARK_OVERLAP_DAY] [int] NULL,
    CONSTRAINT [CK_SOURCE_OBJECT_ORIGIN] CHECK (
        [OBJECT_ORIGIN] IS NULL
        OR [OBJECT_ORIGIN] IN ('DWH', 'SOURCE')
    ),
    CONSTRAINT [PK_SOURCE_OBJECT] PRIMARY KEY CLUSTERED ([OBJECT_ID] ASC),
    CONSTRAINT [UQ_SOURCE_OBJECT] UNIQUE NONCLUSTERED (
        [SOURCE_SYSTEM] ASC,
        [SERVER_NAME] ASC,
        [DATABASE_NAME] ASC,
        [SCHEMA_NAME] ASC,
        [OBJECT_NAME] ASC
    ),
    CONSTRAINT [CK_SOURCE_OBJECT_DWH_LAYER] CHECK (
        [DWH_LAYER] IS NULL
        OR [DWH_LAYER] IN ('META', 'MAP', 'MART', 'FACT', 'DIM', 'STG', 'INT', 'REF', 'LAND')
    )
) ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IX_SOURCE_OBJECT_BUSINESS_DOMAIN]
    ON [META].[SOURCE_OBJECT] ([BUSINESS_DOMAIN_ID] ASC)
    ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IX_SOURCE_OBJECT_DWH_LAYER]
    ON [META].[SOURCE_OBJECT] ([DWH_LAYER] ASC)
    ON [PRIMARY];
GO

ALTER TABLE [META].[SOURCE_OBJECT]
ADD CONSTRAINT [DF_SOURCE_OBJECT_CREATED_TS]
DEFAULT (SYSUTCDATETIME()) FOR [CREATED_TS];
GO

ALTER TABLE [META].[SOURCE_OBJECT]
WITH CHECK
ADD CONSTRAINT [FK_SOURCE_OBJECT_BUSINESS_DOMAIN]
FOREIGN KEY ([BUSINESS_DOMAIN_ID])
REFERENCES [META].[BUSINESS_DOMAIN] ([BUSINESS_DOMAIN_ID]);
GO

ALTER TABLE [META].[SOURCE_OBJECT]
CHECK CONSTRAINT [FK_SOURCE_OBJECT_BUSINESS_DOMAIN];
GO

ALTER TABLE [META].[SOURCE_OBJECT]
CHECK CONSTRAINT [CK_SOURCE_OBJECT_DWH_LAYER];
GO
