
ALTER TABLE [META].[SOURCE_OBJECT] DROP CONSTRAINT [DF_SOURCE_OBJECT_CREATED_TS]
GO

/****** Object:  Table [META].[SOURCE_OBJECT]    Script Date: 4. 08. 2026 09:48:59 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[META].[SOURCE_OBJECT]') AND type in (N'U'))
DROP TABLE [META].[SOURCE_OBJECT]
GO

/****** Object:  Table [META].[SOURCE_OBJECT]    Script Date: 4. 08. 2026 09:48:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [META].[SOURCE_OBJECT](
	[OBJECT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SOURCE_SYSTEM] [varchar](100) NOT NULL,
	[SERVER_NAME] [varchar](255) NULL,
	[DATABASE_NAME] [varchar](255) NULL,
	[SCHEMA_NAME] [varchar](255) NULL,
	[OBJECT_NAME] [varchar](255) NOT NULL,
	[LAND_OBJECT_NAME] [varchar](255) NOT NULL,
	[OBJECT_TYPE] [varchar](30) NOT NULL,
	[STATUS] [varchar](20) NOT NULL,
	[LAST_STRUCTURE_HASH] [varbinary](32) NULL,
	[LAST_SEEN_TS] [datetime2](0) NULL,
	[LAST_STRUCTURE_CHANGE_TS] [datetime2](0) NULL,
	[CREATED_TS] [datetime2](0) NOT NULL,
 CONSTRAINT [PK_SOURCE_OBJECT] PRIMARY KEY CLUSTERED 
(
	[OBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SOURCE_OBJECT] UNIQUE NONCLUSTERED 
(
	[SOURCE_SYSTEM] ASC,
	[SERVER_NAME] ASC,
	[DATABASE_NAME] ASC,
	[SCHEMA_NAME] ASC,
	[OBJECT_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [META].[SOURCE_OBJECT] ADD  CONSTRAINT [DF_SOURCE_OBJECT_CREATED_TS]  DEFAULT (sysdatetime()) FOR [CREATED_TS]
GO


