--
--  table: STG_COLUMN_CONFIG
--

CREATE TABLE META.STG_COLUMN_CONFIG
(
    OBJECT_ID              bigint        NOT NULL,
    COLUMN_NAME            varchar(255)  NOT NULL,

    INCLUDE_IN_STG         bit           NOT NULL DEFAULT 1,
    TEXT_STANDARDIZATION   varchar(10)   NOT NULL DEFAULT 'NONE',

    CREATED_TS             datetime2(0)  NOT NULL DEFAULT SYSDATETIME(),
    MODIFIED_TS            datetime2(0)  NULL,

    CONSTRAINT PK_STG_COLUMN_CONFIG
        PRIMARY KEY (OBJECT_ID, COLUMN_NAME),

    CONSTRAINT FK_STG_COLUMN_CONFIG_SOURCE_OBJECT
        FOREIGN KEY (OBJECT_ID)
        REFERENCES META.SOURCE_OBJECT (OBJECT_ID),

    CONSTRAINT CK_STG_COLUMN_CONFIG_TEXT_STANDARDIZATION
        CHECK (TEXT_STANDARDIZATION IN ('NONE', 'LOWER', 'UPPER'))
);
