SELECT NO,
        LASTNAME,
        FIRSTNAME,
        ADDRESS,
        CITY,
        STATE,
        PHONE,
        MOBILEPHONE, 
        FAX, 
        ID, 
        DEPARTMENT,
        SUBDEPARTMENT,
        DIVISION,
        HOST,
        EMAIL,
        ORGNO,
        ADDITIONAL_FIELD_1,
        ADDITIONAL_FIELD_2,
        BLOCKED,
        ACTIVE,
        SRC_SYSTEM,
        LOAD_TS
    FROM {{ ref('tsspica_users') }};